name: ${project.artifactId}
main: net.tenrem.doorcloser.DoorCloserPlugin
version: ${project.version}
api-version: 1.13
authors: [Pete Brown 10rem.net, Maingron]
commands:
   dcreload:
      description: Reload the configuration file.
      usage: "Usage: '/dcreload' to reload configuration file."
      permission: tenrem.doorcloser.reload
      permission-message: You don't have permission to reload the configuration file.
   
   